networks:
  internal:
  alwatr-public-network:
    name: alwatr-public-network
    external: true

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    networks:
      alwatr-public-network:

    environment:
      - NGINX_DISALLOW_ROBOTS=${NGINX_DISALLOW_ROBOTS:-}

    labels:
      traefik.enable: true
      traefik.port: 80
      traefik.frontend.rule: Host:${domain}; PathPrefix:/;
      traefik.frontend.entryPoints: http, https
      traefik.frontend.redirect.entryPoint: https
